### ISSUE TITLE
Если передается пустой endpoint игнорировать

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/lib_ngstd#7]
Сейчас при передаче в библиотеку пустого endpoint он устанавливается. Это не нормальная ситуация когда endpoint пустой. Нужно просто игнорировать такое значение и оставлять значение по-умолчанию.

https://github.com/nextgis/lib_ngstd/blob/master/src/framework/access/access.cpp#L247

**Comment by 514ckw4r3** [comment]
Fixed: [commit/2b58eb5cc2e53f5f1660307c82f3b09b46ab03b2](https://github.com/nextgis/lib_ngstd/commit/2b58eb5cc2e53f5f1660307c82f3b09b46ab03b2)
